// <auto-generated />
using System;
using System.Resources;
using System.Globalization;

namespace RegulationAssistantChatClient.Properties
{
	/// <summary>
	/// Strongly-typed resource class for accessing localized strings.
	/// Provides access to the resource manager and culture override for lookups.
	/// </summary>
	internal static class Resources
	{
		/// <summary>
		/// Backing field for the <see cref="ResourceManager"/> instance.
		/// Lazily initialized on first access.
		/// </summary>
		private static ResourceManager resourceMan;

		/// <summary>
		/// Backing field for the <see cref="Culture"/> used for resource lookups.
		/// When null the current thread's <see cref="CultureInfo.CurrentUICulture"/> is used.
		/// </summary>
		private static CultureInfo resourceCulture;

		/// <summary>
		/// Returns the cached <see cref="ResourceManager"/> instance, creating it if necessary.
		/// The manager is used to retrieve localized resources from the assembly.
		/// </summary>
		internal static ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					resourceMan = new ResourceManager("RegulationAssistantChatClient.Properties.Resources", typeof(Resources).Assembly);
				}

				return resourceMan;
			}
		}

		/// <summary>
		/// Overrides the current thread's <see cref="CultureInfo.CurrentUICulture"/> for all resource lookups using this strongly typed resource class.
		/// Set this property to force resource lookups to use a specific culture.
		/// </summary>
		internal static CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}

			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		/// Gets the localized value for the "WelcomeMessage" resource key.
		/// </summary>
		internal static string WelcomeMessage
		{
			get
			{
				return ResourceManager.GetString("WelcomeMessage", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the localized value for the "SendButton" resource key.
		/// </summary>
		internal static string SendButton
		{
			get
			{
				return ResourceManager.GetString("SendButton", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the localized value for the "ClearButton" resource key.
		/// </summary>
		internal static string ClearButton
		{
			get
			{
				return ResourceManager.GetString("ClearButton", resourceCulture);
			}
		}
	}
}
