// <auto-generated />
using System;
using System.Resources;
using System.Globalization;

namespace RegulationAssistantChatClient.Properties
{
	/// <summary>
	/// Strongly-typed resource class for accessing localized strings.
	/// Provides access to the resource manager and culture override for lookups.
	/// </summary>
	public static class Resources
	{
		/// <summary>
		/// Backing field for the <see cref="ResourceManager"/> instance.
		/// Lazily initialized on first access.
		/// </summary>
		private static ResourceManager resourceMan;

		/// <summary>
		/// Backing field for the <see cref="Culture"/> used for resource lookups.
		/// When null the current thread's <see cref="CultureInfo.CurrentUICulture"/> is used.
		/// </summary>
		private static CultureInfo resourceCulture;

		/// <summary>
		/// Returns the cached <see cref="ResourceManager"/> instance, creating it if necessary.
		/// The manager is used to retrieve localized resources from the assembly.
		/// </summary>
		public static ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					resourceMan = new ResourceManager("RegulationAssistantChatClient.Properties.Resources", typeof(Resources).Assembly);
				}

				return resourceMan;
			}
		}

		/// <summary>
		/// Overrides the current thread's <see cref="CultureInfo.CurrentUICulture"/> for all resource lookups using this strongly typed resource class.
		/// Set this property to force resource lookups to use a specific culture.
		/// </summary>
		public static CultureInfo Culture
		{
			get { return resourceCulture; }
			set { resourceCulture = value; }
		}

		/// <summary>
		/// Gets the localized value for the "WelcomeMessage" resource key.
		/// </summary>
		public static string WelcomeMessage => ResourceManager.GetString("WelcomeMessage", resourceCulture);

		/// <summary>
		/// Gets the localized value for the "SendButton" resource key.
		/// </summary>
		public static string SendButton => ResourceManager.GetString("SendButton", resourceCulture);

		/// <summary>
		/// Gets the localized value for the "ClearButton" resource key.
		/// </summary>
		public static string ClearButton => ResourceManager.GetString("ClearButton", resourceCulture);

		/// <summary>
		/// Gets the localized value for the "DateLabel" resource key.
		/// </summary>
		public static string DateLabel => ResourceManager.GetString("DateLabel", resourceCulture);

		/// <summary>
		/// Gets the localized value for the "Documents_TitleHeader" resource key.
		/// </summary>
		public static string Documents_TitleHeader => ResourceManager.GetString("Documents_TitleHeader", resourceCulture);

		/// <summary>
		/// Gets the localized value for the "Documents_VersionHeader" resource key.
		/// </summary>
		public static string Documents_VersionHeader => ResourceManager.GetString("Documents_VersionHeader", resourceCulture);

		/// <summary>
		/// Gets the localized value for the "Documents_ValidFromHeader" resource key.
		/// </summary>
		public static string Documents_ValidFromHeader => ResourceManager.GetString("Documents_ValidFromHeader", resourceCulture);

		/// <summary>
		/// Gets the localized value for the "Documents_ValidToHeader" resource key.
		/// </summary>
		public static string Documents_ValidToHeader => ResourceManager.GetString("Documents_ValidToHeader", resourceCulture);

		/// <summary>
		/// Gets the localized value for the "NewButton" resource key.
		/// </summary>
		public static string NewButton => ResourceManager.GetString("NewButton", resourceCulture);

		/// <summary>
		/// Gets the localized value for the "UploadButton" resource key.
		/// </summary>
		public static string UploadButton => ResourceManager.GetString("UploadButton", resourceCulture);

		/// <summary>
		/// Gets the localized value for the "EditButton" resource key.
		/// </summary>
		public static string EditButton => ResourceManager.GetString("EditButton", resourceCulture);

		/// <summary>
		/// Gets the localized value for the "DeleteButton" resource key.
		/// </summary>
		public static string DeleteButton => ResourceManager.GetString("DeleteButton", resourceCulture);

		/// <summary>
		/// Gets the localized value for the "DocumentTitle_Prompt" resource key.
		/// </summary>
		public static string DocumentTitle_Prompt => ResourceManager.GetString("DocumentTitle_Prompt", resourceCulture);

		/// <summary>
		/// Gets the localized value for the "DocumentTitle_Save" resource key.
		/// </summary>
		public static string DocumentTitle_Save => ResourceManager.GetString("DocumentTitle_Save", resourceCulture);

		/// <summary>
		/// Gets the localized value for the "DocumentTitle_Cancel" resource key.
		/// </summary>
		public static string DocumentTitle_Cancel => ResourceManager.GetString("DocumentTitle_Cancel", resourceCulture);

		/// <summary>
		/// Gets the localized value for the "DocumentTitle_Required" resource key.
		/// </summary>
		public static string DocumentTitle_Required => ResourceManager.GetString("DocumentTitle_Required", resourceCulture);

		/// <summary>
		/// Gets the localized value for the "Upload_Failed" resource key.
		/// </summary>
		public static string Upload_Failed => ResourceManager.GetString("Upload_Failed", resourceCulture);

		/// <summary>
		/// Gets the localized value for the "Upload_ErrorTitle" resource key.
		/// </summary>
		public static string Upload_ErrorTitle => ResourceManager.GetString("Upload_ErrorTitle", resourceCulture);

		/// <summary>
		/// Gets the localized value for the "Upload_ErrorDetail" resource key.
		/// </summary>
		public static string Upload_ErrorDetail => ResourceManager.GetString("Upload_ErrorDetail", resourceCulture);

		/// <summary>
		/// Gets the localized value for the "DocumentNotFound_Title" resource key.
		/// </summary>
		public static string DocumentNotFound_Title => ResourceManager.GetString("DocumentNotFound_Title", resourceCulture);

		/// <summary>
		/// Gets the localized value for the "DocumentNotFound_Message" resource key.
		/// </summary>
		public static string DocumentNotFound_Message => ResourceManager.GetString("DocumentNotFound_Message", resourceCulture);

		/// <summary>
		/// Gets the localized value for the "SaveChanges_Prompt" resource key.
		/// </summary>
		public static string SaveChanges_Prompt => ResourceManager.GetString("SaveChanges_Prompt", resourceCulture);

		/// <summary>
		/// Gets the localized value for the "SaveChanges_Title" resource key.
		/// </summary>
		public static string SaveChanges_Title => ResourceManager.GetString("SaveChanges_Title", resourceCulture);
	}
}
